
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required=["git.containerum.net/ch/kube-client"]

[prune]
  non-go = true
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "git.containerum.net/ch/kube-client"
    non-go = false

[[constraint]]
  name = "git.containerum.net/ch/kube-client"
  version = "~0.10.1"

[[constraint]]
  name = "github.com/appleboy/gofight"
  version = "2.0.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "github.com/google/uuid"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.5"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/api-gateway"
