required = ["github.com/containerum/kube-client"]

[prune]
  non-go = true
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "github.com/containerum/kube-client"
    non-go = false

  [[prune.project]]
    name = "github.com/containerum/utils"
    non-go = false

  [[prune.project]]
    name = "github.com/containerum/cherry"
    non-go = false

[[constraint]]
  name = "github.com/appleboy/gofight"
  version = "2.0.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "github.com/google/uuid"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.5"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[constraint]]
  name = "github.com/containerum/utils"
  version = "1.0.0"

[[constraint]]
  name = "github.com/containerum/kube-client"
  version = "^0.23.23"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.9.3"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "^1.1.0"
