swagger: "2.0"
parameters:
  UserIDHeader:
    $ref: "vendor/github.com/containerum/utils/httputil/swagger.json#/parameters/UserIDHeader"
  UserRoleHeader:
    $ref: "vendor/github.com/containerum/utils/httputil/swagger.json#/parameters/UserRoleHeader"
  UpgradeHeader:
    name: Upgrade
    in: header
    type: string
    format: string
    required: true
  ConnectionHeader:
    name: Connection
    in: header
    type: string
    format: string
    required: true
  SecWebSocketKeyHeader:
    name: Sec-WebSocket-Key
    in: header
    type: string
    format: string
    required: true
  SecWebsocketVersionHeader:
    name: Sec-Websocket-Version
    in: header
    type: integer
    format: int
    required: true
responses:
  error:
    description: cherry error
    schema:
      $ref: "vendor/github.com/containerum/cherry/swagger.json#/definitions/Err"